import { createClient } from '@/lib/supabase/server';

export default async function Production(){
  const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(user)await supabase.rpc('claim_pending_memberships');const {data:orgs}=await supabase.rpc('get_my_organizations');const org=orgs?.[0];
  if(!org)return <div className="card"><h1>Production</h1><p>Your workspace must be active.</p></div>;
  const orgId=org.organization_id;
  const [jobsResult,scheduleResult,materialsResult,qualityResult,serviceResult,inventoryResult,purchaseResult]=await Promise.all([
    supabase.from('production_jobs').select('id',{count:'exact',head:true}).eq('organization_id',orgId),
    supabase.from('production_schedule_events').select('id',{count:'exact',head:true}).eq('organization_id',orgId),
    supabase.from('material_requests').select('id',{count:'exact',head:true}).eq('organization_id',orgId),
    supabase.from('quality_inspections').select('id',{count:'exact',head:true}).eq('organization_id',orgId),
    supabase.from('service_requests').select('id',{count:'exact',head:true}).eq('organization_id',orgId),
    supabase.from('inventory_items').select('id',{count:'exact',head:true}).eq('organization_id',orgId),
    supabase.from('purchase_orders').select('id',{count:'exact',head:true}).eq('organization_id',orgId),
  ]);
  const {data:jobs}=await supabase.from('production_jobs').select('id,work_order_number,project_name,project_type,status,start_date,estimated_completion_date,contractor_name').eq('organization_id',orgId).order('created_at',{ascending:false}).limit(20);
  const metrics=[['Active / total jobs',jobsResult.count||0],['Schedule events',scheduleResult.count||0],['Material requests',materialsResult.count||0],['Quality inspections',qualityResult.count||0],['Service requests',serviceResult.count||0],['Inventory items',inventoryResult.count||0],['Purchase orders',purchaseResult.count||0]];
  return <><div className="top"><div><h1>Production</h1><p>Scheduling, remeasure, crews, job board, quality, service, inventory, material purchasing, and closeout all live under Production.</p></div></div><section className="grid">{metrics.slice(0,4).map(([label,value])=><div className="card metric" key={String(label)}><span>{label}</span><strong>{value}</strong></div>)}</section><section className="module-grid section"><div className="card"><h3>Scheduling & Remeasure</h3><strong>{scheduleResult.count||0} events</strong><p>Production-owned scheduling and 2-hour remeasure slots from 10 AM–6 PM with production-manager acknowledgement.</p></div><div className="card"><h3>Crews & Notifications</h3><p>Assign contractor crews and notify all parties tied to the job when crews or schedules change.</p></div><div className="card"><h3>Inventory & Purchasing</h3><strong>{inventoryResult.count||0} inventory / {purchaseResult.count||0} POs</strong><p>Stock, costs, material requests, purchase orders, deliveries, and job allocation.</p></div><div className="card"><h3>Quality & Service</h3><strong>{qualityResult.count||0} inspections / {serviceResult.count||0} service</strong><p>Quality inspections, punch items, warranty/service requests, activity, and closeout.</p></div><div className="card"><h3>Material Requests</h3><strong>{materialsResult.count||0}</strong><p>Requests, approvals, purchase status, deliveries, and issues.</p></div><div className="card"><h3>Job Completion</h3><p>Contract review through final walk, closeout, collection, and warranty handoff.</p></div></section><div className="card section"><h2>Production Job Board</h2><table className="table"><thead><tr><th>Work order</th><th>Project</th><th>Type</th><th>Status</th><th>Start</th><th>Est. completion</th><th>Contractor</th></tr></thead><tbody>{jobs?.length?jobs.map((job:any)=><tr key={job.id}><td>{job.work_order_number||'—'}</td><td>{job.project_name}</td><td>{job.project_type||'—'}</td><td><span className="pill">{String(job.status).replaceAll('_',' ')}</span></td><td>{job.start_date||'—'}</td><td>{job.estimated_completion_date||'—'}</td><td>{job.contractor_name||'Unassigned'}</td></tr>):<tr><td colSpan={7}>No production jobs yet. Signed contracts will enter Production automatically.</td></tr>}</tbody></table></div></>;
}
