'use client';

import { FormEvent, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

type AcceptedProposal={id:string;estimate_id:string;proposal_number:string;title:string;accepted_by_name:string|null;estimate:{id:string;project_name:string|null;project_address:string|null;ninety_day_price:number;today_price:number}};

export function ContractBuilder({organizationId,userId,proposals}:{organizationId:string;userId:string;proposals:AcceptedProposal[]}){
  const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);const [promo,setPromo]=useState('no_payments_no_interest');
  async function submit(e:FormEvent<HTMLFormElement>){
    e.preventDefault();setSaving(true);setMessage('');const fd=new FormData(e.currentTarget);const proposal=proposals.find(p=>p.id===String(fd.get('proposal')));if(!proposal){setMessage('Choose an accepted proposal.');setSaving(false);return;}
    const contractPrice=Number(proposal.estimate.today_price||0);const down=Number(fd.get('downPayment')||0);const months=Number(fd.get('promoMonths')||0);const paymentTerms=promo==='no_payments_no_interest'?`No payments / no interest${months?` for ${months} months`:''}`:`No payments / deferred interest${months?` for ${months} months`:''}`;
    const contractNumber=`PRC-${new Date().getFullYear()}-${Date.now().toString().slice(-6)}`;const supabase=createClient();
    const {error}=await supabase.from('contracts').insert({organization_id:organizationId,estimate_id:proposal.estimate_id,contract_number:contractNumber,customer_name:String(fd.get('homeowner')||proposal.accepted_by_name||'Customer'),co_homeowner_name:String(fd.get('coHomeowner')||'')||null,customer_email:String(fd.get('email')||'')||null,customer_phone:String(fd.get('phone')||'')||null,project_address:proposal.estimate.project_address||'',status:'draft',ninety_day_price:Number(proposal.estimate.ninety_day_price||0),contract_price:contractPrice,down_payment:down,balance_due:Math.max(0,contractPrice-down),payment_terms:paymentTerms,payment_method:String(fd.get('paymentMethod')),payment_schedule:{promotion:promo,promotion_months:months},warranty_terms:'5-year labor warranty unless superseded by project-specific terms.',general_terms:{proposal_id:proposal.id,proposal_number:proposal.proposal_number,promotion:promo,promotion_months:months},representative_name:String(fd.get('representative')||''),co_representative_name:String(fd.get('coRepresentative')||'')||null,cancellation_notice_acknowledged:false,created_by:userId});
    if(error){setMessage(error.message);setSaving(false);return;}setMessage(`${contractNumber} created from the accepted proposal. It is ready for contract review and signatures.`);setSaving(false);
  }
  return <form className="card" onSubmit={submit}><h2>Create Contract</h2><p>Only accepted proposals can be converted into a contract.</p><div className="form-grid"><label className="field">Accepted proposal<select name="proposal" required>{proposals.map(p=><option value={p.id} key={p.id}>{p.proposal_number} — {p.title}</option>)}</select></label><label className="field">Homeowner<input name="homeowner" defaultValue={proposals[0]?.accepted_by_name||''} required/></label><label className="field">Co-homeowner<input name="coHomeowner"/></label><label className="field">Customer email<input name="email" type="email"/></label><label className="field">Customer phone<input name="phone"/></label><label className="field">Representative<input name="representative" defaultValue="Chris Sosa"/></label><label className="field">Second representative<input name="coRepresentative"/></label><label className="field">Payment method<select name="paymentMethod"><option value="financing">Financing</option><option value="cash">Cash</option><option value="check">Check</option><option value="card">Card</option></select></label><label className="field">Promotional terms<select value={promo} onChange={e=>setPromo(e.target.value)}><option value="no_payments_no_interest">No payments / no interest</option><option value="no_payments_deferred_interest">No payments / deferred interest</option></select></label><label className="field">Promotion months<select name="promoMonths" defaultValue="12"><option value="6">6 months</option><option value="12">12 months</option><option value="18">18 months</option><option value="24">24 months</option><option value="36">36 months</option></select></label><label className="field">Down payment<input name="downPayment" type="number" min="0" step="0.01" defaultValue="0"/></label></div>{message&&<p>{message}</p>}<div className="modal-actions"><button className="primary button-auto" disabled={saving||!proposals.length}>{saving?'Creating…':'Create Contract'}</button></div></form>;
}
