'use client';

import { FormEvent, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

type AcceptedProposal={id:string;estimate_id:string;proposal_number:string;title:string;accepted_by_name:string|null;estimate:{id:string;project_name:string|null;project_address:string|null;ninety_day_price:number;today_price:number}};
type SalesRep={workforceMemberId:string;linkedUserId:string|null;name:string;jobTitle:string|null;branchId:string|null;activationStatus:string};

export function ContractBuilder({organizationId,userId,proposals,salesReps}:{organizationId:string;userId:string;proposals:AcceptedProposal[];salesReps:SalesRep[]}){
  const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);const [promo,setPromo]=useState('no_payments_no_interest');const [paymentMethod,setPaymentMethod]=useState('finance');
  const defaultRep=salesReps.find(rep=>rep.linkedUserId===userId)?.name||salesReps[0]?.name||'';
  async function submit(e:FormEvent<HTMLFormElement>){
    e.preventDefault();setSaving(true);setMessage('');const fd=new FormData(e.currentTarget);const proposal=proposals.find(p=>p.id===String(fd.get('proposal')));if(!proposal){setMessage('Choose an accepted proposal.');setSaving(false);return;}
    const contractPrice=Number(proposal.estimate.today_price||0);const down=Number(fd.get('downPayment')||0);const months=paymentMethod==='finance'?Number(fd.get('promoMonths')||0):0;const paymentTerms=paymentMethod==='cash'?'Cash payment terms':promo==='no_payments_no_interest'?`No payments / no interest${months?` for ${months} months`:''}`:`No payments / deferred interest${months?` for ${months} months`:''}`;
    const primary=String(fd.get('representative')||'');const secondary=String(fd.get('coRepresentative')||'');
    if(!primary){setMessage('Choose the primary sales representative.');setSaving(false);return;}
    if(primary===secondary){setMessage('Primary and second representative must be different.');setSaving(false);return;}
    const contractNumber=`PRC-${new Date().getFullYear()}-${Date.now().toString().slice(-6)}`;const supabase=createClient();
    const {error}=await supabase.from('contracts').insert({organization_id:organizationId,estimate_id:proposal.estimate_id,contract_number:contractNumber,customer_name:String(fd.get('homeowner')||proposal.accepted_by_name||'Customer'),co_homeowner_name:String(fd.get('coHomeowner')||'')||null,customer_email:String(fd.get('email')||'')||null,customer_phone:String(fd.get('phone')||'')||null,project_address:proposal.estimate.project_address||'',status:'draft',ninety_day_price:Number(proposal.estimate.ninety_day_price||0),contract_price:contractPrice,down_payment:down,balance_due:Math.max(0,contractPrice-down),payment_terms:paymentTerms,payment_method:paymentMethod,payment_schedule:{promotion:paymentMethod==='finance'?promo:null,promotion_months:months},warranty_terms:'5-year labor warranty unless superseded by project-specific terms.',general_terms:{proposal_id:proposal.id,proposal_number:proposal.proposal_number,promotion:paymentMethod==='finance'?promo:null,promotion_months:months},representative_name:primary,co_representative_name:secondary||null,cancellation_notice_acknowledged:false,created_by:userId});
    if(error){setMessage(error.message);setSaving(false);return;}await supabase.from('estimates').update({selected_for_contract:true,updated_by:userId}).eq('id',proposal.estimate_id);setMessage(`${contractNumber} created from the accepted proposal. It is ready for contract review and signatures.`);setSaving(false);
  }
  return <form className="card" onSubmit={submit}><h2>Create Contract</h2><p>Only accepted proposals can be converted into a contract. Representatives come from the active Proper OS sales roster.</p><div className="form-grid"><label className="field">Accepted proposal<select name="proposal" required>{proposals.map(p=><option value={p.id} key={p.id}>{p.proposal_number} — {p.title}</option>)}</select></label><label className="field">Homeowner<input name="homeowner" defaultValue={proposals[0]?.accepted_by_name||''} required/></label><label className="field">Co-homeowner<input name="coHomeowner"/></label><label className="field">Customer email<input name="email" type="email"/></label><label className="field">Customer phone<input name="phone"/></label><label className="field">Representative<select name="representative" defaultValue={defaultRep} required><option value="" disabled>Select representative</option>{salesReps.map(rep=><option key={rep.workforceMemberId} value={rep.name}>{rep.name}{rep.jobTitle?` — ${rep.jobTitle}`:''}</option>)}</select></label><label className="field">Second representative<select name="coRepresentative" defaultValue=""><option value="">None</option>{salesReps.map(rep=><option key={rep.workforceMemberId} value={rep.name}>{rep.name}{rep.jobTitle?` — ${rep.jobTitle}`:''}</option>)}</select></label><label className="field">Payment method<select value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)}><option value="finance">Financing</option><option value="cash">Cash</option></select></label>{paymentMethod==='finance'&&<><label className="field">Promotional terms<select value={promo} onChange={e=>setPromo(e.target.value)}><option value="no_payments_no_interest">No payments / no interest</option><option value="no_payments_deferred_interest">No payments / deferred interest</option></select></label><label className="field">Promotion months<select name="promoMonths" defaultValue="12"><option value="6">6 months</option><option value="12">12 months</option><option value="18">18 months</option><option value="24">24 months</option><option value="36">36 months</option></select></label></>}<label className="field">Down payment<input name="downPayment" type="number" min="0" step="0.01" defaultValue="0"/></label></div>{message&&<p>{message}</p>}<div className="modal-actions"><button className="primary button-auto" disabled={saving||!proposals.length||!salesReps.length}>{saving?'Creating…':'Create Contract'}</button></div></form>;
}
