'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import { createClient } from '@/lib/supabase/client';

type Category={id:string;name:string;slug:string;miscellaneous_fee:number;markup_rate:number;today_discount_rate:number};
type Item={id:string;category_id:string;product_name:string;option_name:string;name:string;sku:string;unit:string;base_unit_price:number;included_allowance_rate:number|null;allowance_mode:string};
type Lead={id:string;customer_id:string|null;first_name:string;last_name:string;email:string|null;phone:string|null;status:string;project_interest:string[];address:string};
type QtyMap=Record<string,number>;

function tierMatch(items:Item[],qty:number){if(items.length===1)return items[0];const under=items.find(i=>/under 20|up to 200/i.test(i.name));const mid=items.find(i=>/20[–-]29/i.test(i.name));const high=items.find(i=>/30\+/i.test(i.name));if(under&&mid&&high){if(qty<20)return under;if(qty<30)return mid;return high;}const under200=items.find(i=>/under 200|up to 200/i.test(i.name));const over200=items.find(i=>/201\+/i.test(i.name));if(under200&&over200)return qty<=200?under200:over200;return items[0];}

export function EstimateBuilder({categories,items,leads,organizationId,userId}:{categories:Category[];items:Item[];leads:Lead[];organizationId:string;userId:string}){
 const [step,setStep]=useState(1),[categoryId,setCategoryId]=useState(categories[0]?.id||''),[leadId,setLeadId]=useState(''),[qty,setQty]=useState<QtyMap>({}),[title,setTitle]=useState(''),[address,setAddress]=useState(''),[notes,setNotes]=useState(''),[message,setMessage]=useState(''),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false);
 const category=categories.find(c=>c.id===categoryId);
 const groups=useMemo(()=>{const map=new Map<string,Item[]>();items.filter(i=>i.category_id===categoryId).forEach(i=>{const key=i.product_name||i.name;map.set(key,[...(map.get(key)||[]),i]);});return [...map.entries()].map(([product,options])=>({product,options}));},[items,categoryId]);
 const selected=groups.map(g=>{const q=Number(qty[g.product]||0),item=tierMatch(g.options,q);return {q,item,product:g.product,line:q*Number(item?.base_unit_price||0)};}).filter(x=>x.q>0&&x.item);
 const base=selected.reduce((s,x)=>s+x.line,0),misc=base>0?Number(category?.miscellaneous_fee||0):0,ninety=(base+misc)*(1+Number(category?.markup_rate||0)),today=ninety*(1-Number(category?.today_discount_rate||0));
 const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
 function chooseLead(id:string){setLeadId(id);const l=leads.find(x=>x.id===id);if(!l)return;const n=`${l.first_name||''} ${l.last_name||''}`.trim();setTitle(n?`${n} — ${category?.name||'Project'}`:`${category?.name||'Project'}`);if(l.address)setAddress(l.address);}
 async function save(){if(!category||!selected.length||!leadId){setMessage('Select a customer and add at least one project measurement.');return;}setSaving(true);setMessage('');const supabase=createClient();const {data:estimate,error}=await supabase.from('estimates').insert({organization_id:organizationId,lead_id:leadId,title:title||`${category.name} Project`,project_name:title||`${category.name} Project`,project_address:address||null,category_slug:category.slug,status:'draft',base_subtotal:base,miscellaneous_fee:misc,markup_rate:category.markup_rate,today_discount_rate:category.today_discount_rate,ninety_day_price:ninety,today_price:today,notes:notes||null,created_by:userId}).select('id,estimate_number').single();if(error){setMessage(error.message);setSaving(false);return;}const rows=selected.map(x=>({estimate_id:estimate.id,organization_id:organizationId,pricing_item_id:x.item.id,sku:x.item.sku,name:x.item.name,unit:x.item.unit,quantity:x.q,unit_price:x.item.base_unit_price,line_total:x.line,allowance_mode:x.item.allowance_mode,included_allowance_rate:x.item.included_allowance_rate}));const {error:itemError}=await supabase.from('estimate_items').insert(rows);if(itemError){setMessage(`Estimate saved, but line items failed: ${itemError.message}`);setSaving(false);return;}setSaved(true);setMessage(`${estimate.estimate_number||'Estimate'} saved. The pricing is locked from the Proper master pricing book and is ready for the AI proposal designer.`);setSaving(false);}
 const steps=['Customer','Project','Measurements & Scope','Pricing Review','AI Proposal'];
 return <><div className="card"><div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:20}}>{steps.map((s,i)=><button key={s} type="button" className={step===i+1?'primary button-auto':'secondary'} onClick={()=>setStep(i+1)}>{i+1}. {s}</button>)}</div>
 {step===1&&<div><h2>Select customer</h2><p>Start from the CRM record so the proposal and contract stay attached to the customer.</p><label className="field">CRM lead / customer<select value={leadId} onChange={e=>chooseLead(e.target.value)}><option value="">Select customer…</option>{leads.map(l=><option value={l.id} key={l.id}>{`${l.first_name||''} ${l.last_name||''}`.trim()||'Unnamed lead'}{l.customer_id?` — ${l.customer_id}`:''}</option>)}</select></label><button className="primary button-auto" disabled={!leadId} onClick={()=>setStep(2)}>Continue to Project</button></div>}
 {step===2&&<div><h2>Project</h2><div className="form-grid"><label className="field">Project category<select value={categoryId} onChange={e=>{setCategoryId(e.target.value);setQty({});}}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field">Project name<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="field">Project address<input value={address} onChange={e=>setAddress(e.target.value)}/></label></div><button className="primary button-auto" onClick={()=>setStep(3)}>Enter Measurements & Scope</button></div>}
 {step===3&&<div><h2>{category?.name} — Measurements & Scope</h2><p>Enter only the quantities that apply. Proper OS automatically selects the correct pricing tier; sales reps do not choose between duplicate price options.</p><table className="table"><thead><tr><th>Work item</th><th>Quantity</th><th>Unit</th></tr></thead><tbody>{groups.map(g=>{const q=Number(qty[g.product]||0),item=tierMatch(g.options,q);return <tr key={g.product}><td><strong>{g.product}</strong>{item?.included_allowance_rate!=null&&<div><small>Allowance up to {money(item.included_allowance_rate)}/{item.unit} included</small></div>}</td><td><input style={{width:110}} type="number" min="0" step="1" value={qty[g.product]||''} onChange={e=>setQty({...qty,[g.product]:Number(e.target.value)})}/></td><td>{String(item?.unit||'').replaceAll('_',' ')}</td></tr>})}</tbody></table><label className="field">Project notes / special instructions<textarea rows={4} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Customer requests, colors, special scope, exclusions, rendering notes…"/></label><button className="primary button-auto" disabled={!selected.length} onClick={()=>setStep(4)}>Review Pricing</button></div>}
 {step===4&&<div><h2>Internal Pricing Review</h2><p>This is the internal calculation screen. These line-item costs and markup mechanics are not shown on the customer proposal.</p><table className="table"><thead><tr><th>Item</th><th>Qty</th><th>Applied master price</th><th>Total</th></tr></thead><tbody>{selected.map(x=><tr key={x.product}><td>{x.product}</td><td>{x.q} {x.item.unit}</td><td>{money(x.item.base_unit_price)}</td><td>{money(x.line)}</td></tr>)}</tbody></table><section className="grid section"><div className="card metric"><span>Base</span><strong>{money(base)}</strong></div><div className="card metric"><span>Misc.</span><strong>{money(misc)}</strong></div><div className="card metric"><span>90-Day</span><strong>{money(ninety)}</strong></div><div className="card metric"><span>Today</span><strong>{money(today)}</strong></div></section><button className="primary button-auto" onClick={save} disabled={saving||saved}>{saving?'Saving…':saved?'Estimate Saved':'Approve Pricing & Save Estimate'}</button>{message&&<p>{message}</p>}{saved&&<button className="secondary" onClick={()=>setStep(5)}>Continue to AI Proposal</button>}</div>}
 {step===5&&<div><h2>AI Proposal Designer</h2><p>The estimate remains the pricing source of truth. AI uses the customer, project, scope, notes, allowances, pricing and future uploaded project images to build the customer-facing Proper Remodeling proposal.</p><div className="card" style={{border:'2px solid #2f7d32'}}><h3>Ready to create the customer proposal</h3><p><strong>{title}</strong><br/>{category?.name} · Today&apos;s investment {money(today)}</p><p>The proposal will use the approved Proper Remodeling brochure presentation rather than exposing estimator pricing options.</p><Link className="primary button-auto link-button" href="/proposals">Generate AI Proposal</Link></div></div>}
 </div></>;
}
