'use client';

import { useState } from 'react';
import Link from 'next/link';
import { createClient } from '@/lib/supabase/client';

type Estimate={id:string;estimate_number:string|null;project_name:string|null;title:string;project_address:string|null;category_slug:string;ninety_day_price:number;today_price:number;status:string};
type AIContent={headline?:string;project_subtitle?:string;introduction?:string;scope_title?:string;scope_summary?:string;scope_bullets?:string[];benefits?:string[];allowance_notes?:string[];warranty_summary?:string;investment_label?:string;closing?:string};
type ProposalContent={ai?:AIContent;customer?:{name?:string;email?:string|null;phone?:string|null};project?:{name?:string;address?:string|null;category?:string};pricing?:{ninety_day?:number;today?:number}};
type Proposal={id:string;estimate_id:string;proposal_number:string;title:string;status:string;scope_summary:string|null;proposal_content:ProposalContent|null;accepted_by_name:string|null;accepted_at:string|null;created_at:string};

const company={name:'Proper Remodeling',phone:'(737) 217-9539',website:'properremodelingllc.com',address:'4175 Freidrich Ln, Suite 203, Austin, TX 78744'};

export function ProposalWorkflow({estimates,initialProposals}:{organizationId:string;userId:string;estimates:Estimate[];initialProposals:Proposal[]}){
  const [proposals,setProposals]=useState(initialProposals),[message,setMessage]=useState(''),[previewId,setPreviewId]=useState<string|null>(null),[generatingId,setGeneratingId]=useState<string|null>(null);
  const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n||0));
  const estimateFor=(p:Proposal)=>estimates.find(e=>e.id===p.estimate_id);
  async function generate(e:Estimate){setMessage('');setGeneratingId(e.id);try{const res=await fetch('/api/ai/proposal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({estimateId:e.id})});const payload=await res.json();if(!res.ok){setMessage(payload.error||'AI proposal generation failed.');return;}const p=payload.proposal as Proposal;setProposals([p,...proposals]);setPreviewId(p.id);setMessage(`${p.proposal_number} created by the AI Proposal Designer from the locked Proper estimate.`);}finally{setGeneratingId(null);}}
  async function accept(p:Proposal){const name=window.prompt('Customer name accepting this proposal:');if(!name)return;const supabase=createClient();const acceptedAt=new Date().toISOString();const {error}=await supabase.from('customer_proposals').update({status:'accepted',accepted_by_name:name,accepted_at:acceptedAt}).eq('id',p.id);if(error){setMessage(error.message);return;}setProposals(proposals.map(x=>x.id===p.id?{...x,status:'accepted',accepted_by_name:name,accepted_at:acceptedAt}:x));setMessage('Proposal accepted. Create Contract is now available.');}
  const hasProposal=(estimateId:string)=>proposals.some(p=>p.estimate_id===estimateId);const preview=proposals.find(p=>p.id===previewId);const pe=preview?estimateFor(preview):undefined;const ai=preview?.proposal_content?.ai;
  return <>{message&&<div className="card section"><p>{message}</p></div>}
  <div className="card section"><h2>Estimates ready for AI proposal</h2><p>The estimator controls pricing. AI only creates the customer-facing presentation and scope language.</p><table className="table"><thead><tr><th>Estimate</th><th>Project</th><th>90-Day</th><th>Today</th><th>Action</th></tr></thead><tbody>{estimates.length?estimates.map(e=><tr key={e.id}><td>{e.estimate_number||'Draft'}</td><td>{e.project_name||e.title}</td><td>{money(e.ninety_day_price)}</td><td>{money(e.today_price)}</td><td>{hasProposal(e.id)?<span className="pill">Proposal generated</span>:<button className="primary button-auto" disabled={generatingId===e.id} onClick={()=>generate(e)}>{generatingId===e.id?'Designing…':'Generate AI Proposal'}</button>}</td></tr>):<tr><td colSpan={5}>No saved estimates yet.</td></tr>}</tbody></table></div>
  <div className="card section"><h2>Customer proposals</h2><table className="table"><thead><tr><th>Proposal</th><th>Project</th><th>Status</th><th>Accepted by</th><th>Next step</th></tr></thead><tbody>{proposals.length?proposals.map(p=><tr key={p.id}><td>{p.proposal_number}</td><td>{p.title}</td><td><span className="pill">{p.status}</span></td><td>{p.accepted_by_name||'—'}</td><td style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="secondary" onClick={()=>setPreviewId(p.id)}>View Proposal</button>{p.status==='accepted'?<Link className="primary button-auto link-button" href={`/contracts?proposal=${p.id}`}>Create Contract</Link>:<button className="secondary" onClick={()=>accept(p)}>Accept Proposal</button>}</td></tr>):<tr><td colSpan={5}>No proposals generated yet.</td></tr>}</tbody></table></div>
  {preview&&pe&&<section className="card section" style={{padding:0,overflow:'hidden',background:'#fff'}}><div style={{background:'#111',color:'#fff',padding:'24px 28px',display:'flex',justifyContent:'space-between',gap:18,flexWrap:'wrap',borderBottom:'6px solid #3b8d2f'}}><div><div style={{fontSize:30,fontWeight:900}}>{company.name}</div><div style={{color:'#88c540',fontWeight:700}}>CUSTOMER PROPOSAL</div></div><div style={{fontSize:13,lineHeight:1.6,textAlign:'right'}}>{company.phone}<br/>{company.website}<br/>{company.address}</div></div><div style={{padding:28,display:'grid',gap:24}}>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:16}}><div><small>PROPOSAL</small><h3 style={{margin:'4px 0'}}>{preview.proposal_number}</h3><div>{new Date(preview.created_at).toLocaleDateString()}</div></div><div><small>CUSTOMER</small><h3 style={{margin:'4px 0'}}>{preview.proposal_content?.customer?.name||preview.accepted_by_name||'Customer'}</h3><div>{pe.project_address||'Project address on file'}</div></div></div>
    <div style={{borderLeft:'5px solid #3b8d2f',paddingLeft:18}}><h1 style={{margin:'0 0 6px',fontSize:30}}>{ai?.headline||pe.project_name||pe.title}</h1><p style={{margin:0,fontSize:17}}>{ai?.project_subtitle||pe.category_slug.replaceAll('-',' ')}</p></div>
    {ai?.introduction&&<p style={{fontSize:16,lineHeight:1.65,margin:0}}>{ai.introduction}</p>}
    <div><h2>{ai?.scope_title||'Scope of Work'}</h2><p style={{fontSize:16,lineHeight:1.6}}>{ai?.scope_summary||preview.scope_summary||'Work according to the approved estimate.'}</p>{ai?.scope_bullets?.length?<ul style={{lineHeight:1.8}}>{ai.scope_bullets.map((b,i)=><li key={i}>{b}</li>)}</ul>:null}</div>
    {ai?.benefits?.length?<div><h3>Project Benefits</h3><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10}}>{ai.benefits.map((b,i)=><div key={i} style={{border:'1px solid #ddd',borderRadius:10,padding:14}}>✓ {b}</div>)}</div></div>:null}
    {ai?.allowance_notes?.length?<div><h3>Included Allowances</h3><ul style={{lineHeight:1.7}}>{ai.allowance_notes.map((b,i)=><li key={i}>{b}</li>)}</ul></div>:null}
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:14}}><div style={{border:'1px solid #ddd',borderRadius:12,padding:18}}><small>90-DAY CONTRACT PRICE</small><div style={{fontSize:28,fontWeight:800,marginTop:6}}>{money(pe.ninety_day_price)}</div></div><div style={{border:'3px solid #2f6f27',borderRadius:12,padding:18}}><small>{ai?.investment_label||"TODAY'S INVESTMENT"}</small><div style={{fontSize:32,fontWeight:900,marginTop:6}}>{money(pe.today_price)}</div></div></div>
    {ai?.warranty_summary&&<div style={{background:'#f5f7f4',borderRadius:12,padding:18}}><strong>Our Promise</strong><p style={{marginBottom:0}}>{ai.warranty_summary}</p></div>}
    {ai?.closing&&<p style={{fontSize:16,lineHeight:1.6}}>{ai.closing}</p>}
    <div style={{borderTop:'1px solid #ddd',paddingTop:18,display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><div>{preview.status==='accepted'?<><strong>Accepted by {preview.accepted_by_name}</strong><br/><small>{preview.accepted_at?new Date(preview.accepted_at).toLocaleString():''}</small></>:<span className="pill">Awaiting customer acceptance</span>}</div><div style={{display:'flex',gap:8}}><button className="secondary" onClick={()=>setPreviewId(null)}>Close</button>{preview.status!=='accepted'&&<button className="primary button-auto" onClick={()=>accept(preview)}>Accept Proposal</button>}{preview.status==='accepted'&&<Link className="primary button-auto link-button" href={`/contracts?proposal=${preview.id}`}>Create Contract</Link>}</div></div>
  </div></section>}</>;
}
