'use client';

import { FormEvent, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

type Training={id:string;track:string;content_type:string;title:string;description:string|null;content_category:string;product_category:string|null;is_published:boolean;uploaded_file_name:string|null};
const tracks=[['Company','company'],['Sales','sales'],['Canvassing','canvassing'],['Telemarketing','telemarketing'],['Production','production'],['Marketing','marketing'],['Accounting','accounting'],['Human Resources','human_resources'],['Subcontractors','subcontractors']];
const categories=[['Training','training'],['Product Knowledge','product_knowledge'],['Sales Presentation','sales_presentation'],['Installation','installation'],['Safety','safety'],['Policy','policy'],['Reference','reference']];

export function UniversityManager({organizationId,userId,initialContent}:{organizationId:string;userId:string;initialContent:Training[]}){
  const [content,setContent]=useState(initialContent);const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){
    e.preventDefault();setSaving(true);setMessage('');const form=e.currentTarget;const fd=new FormData(form);const file=fd.get('file');const supabase=createClient();let filePath:string|null=null;let contentType=String(fd.get('contentType'));
    if(file instanceof File&&file.size>0){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');filePath=`${organizationId}/${String(fd.get('track'))}/${Date.now()}-${safe}`;const {error:uploadError}=await supabase.storage.from('training-assets').upload(filePath,file,{contentType:file.type||undefined});if(uploadError){setMessage(uploadError.message);setSaving(false);return;}if(contentType==='module')contentType='document';}
    const external=String(fd.get('externalUrl')||'').trim()||null;if(!filePath&&!external&&contentType!=='module'){setMessage('Upload a file or add an HTTPS link.');setSaving(false);return;}
    const row={organization_id:organizationId,track:String(fd.get('track')),content_type:contentType,title:String(fd.get('title')).trim(),description:String(fd.get('description')||'').trim()||null,duration_minutes:Number(fd.get('duration')||0)||null,file_path:filePath,external_url:external,content_category:String(fd.get('category')),product_category:String(fd.get('productCategory')||'').trim()||'general',is_published:Boolean(fd.get('published')),created_by:userId,uploaded_file_name:file instanceof File&&file.size>0?file.name:null};
    const {data,error}=await supabase.from('training_content').insert(row).select('id,track,content_type,title,description,content_category,product_category,is_published,uploaded_file_name').single();if(error){setMessage(error.message);setSaving(false);return;}setContent([data as Training,...content]);setMessage('Training content added to Proper University.');form.reset();setSaving(false);
  }
  return <><form className="card" onSubmit={submit}><h2>Add training content</h2><p>Training lives in Proper University—not on job boards. Managers can upload videos, presentations, documents, illustrations, modules, or HTTPS resources.</p><div className="form-grid"><label className="field">Track<select name="track" defaultValue="canvassing">{tracks.map(([label,value])=><option value={value} key={value}>{label}</option>)}</select></label><label className="field">Category<select name="category">{categories.map(([label,value])=><option value={value} key={value}>{label}</option>)}</select></label><label className="field">Title<input name="title" required/></label><label className="field">Product category<input name="productCategory" placeholder="General, Roofing, Siding…"/></label><label className="field">Content type<select name="contentType"><option value="video">Video</option><option value="presentation">Presentation</option><option value="document">Document</option><option value="illustration">Illustration</option><option value="module">Module</option></select></label><label className="field">Duration (minutes)<input name="duration" type="number" min="1" max="1440"/></label><label className="field">Upload file<input name="file" type="file"/></label><label className="field">External HTTPS link<input name="externalUrl" type="url" placeholder="https://…"/></label><label className="field form-span-2">Description<textarea name="description" rows={3}/></label><label className="field"><span>Publish now</span><input name="published" type="checkbox"/></label></div>{message&&<p>{message}</p>}<div className="modal-actions"><button className="primary button-auto" disabled={saving}>{saving?'Uploading…':'Add to Proper University'}</button></div></form><div className="card section"><h2>Training library</h2><table className="table"><thead><tr><th>Track</th><th>Category</th><th>Title</th><th>Type</th><th>Status</th></tr></thead><tbody>{content.length?content.map(x=><tr key={x.id}><td>{x.track.replaceAll('_',' ')}</td><td>{x.content_category.replaceAll('_',' ')}</td><td>{x.title}</td><td>{x.content_type}</td><td><span className="pill">{x.is_published?'Published':'Draft'}</span></td></tr>):<tr><td colSpan={5}>No training content yet.</td></tr>}</tbody></table></div></>;
}
