'use client';

import { FormEvent, useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

const jobTitles=['Owner','General Manager','Sales Manager','Sales Representative','Production Manager','Project Manager','Canvassing Manager','Canvasser','Marketing Manager','Telemarketer','Accounting','Office Administrator','Contractor'];
const departments=[['Executive','administration'],['Sales','sales'],['Production','production'],['Canvassing','canvassing'],['Marketing','marketing'],['Telemarketing','telemarketing'],['Accounting','accounting'],['Human Resources','administration']];
const roleMap:Record<string,string>={'Owner':'company_owner','General Manager':'company_manager','Sales Manager':'company_manager','Sales Representative':'sales_rep','Production Manager':'company_manager','Project Manager':'production','Canvassing Manager':'company_manager','Canvasser':'canvassing','Marketing Manager':'company_manager','Telemarketer':'call_center','Accounting':'accounting','Office Administrator':'company_admin','Contractor':'read_only'};
const accessOptions=['Company Pulse','CRM','Estimates','Proposals','Contracts','Production','Canvassing','Marketing','Accounting','Proper University','Reports','Settings'];

type Branch={id:string;name:string};

export default function HumanResources(){
  const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [saving,setSaving]=useState(false); const [branches,setBranches]=useState<Branch[]>([]);
  useEffect(()=>{(async()=>{const supabase=createClient();const {data:orgs}=await supabase.rpc('get_my_organizations');const org=orgs?.[0];if(!org)return;const {data}=await supabase.from('organization_branches').select('id,name').eq('organization_id',org.organization_id).is('deleted_at',null).order('name');setBranches((data||[]) as Branch[]);})();},[]);
  async function submit(event:FormEvent<HTMLFormElement>){
    event.preventDefault();setSaving(true);setError('');setMessage('');const form=event.currentTarget;const fd=new FormData(form);const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();const {data:orgs}=await supabase.rpc('get_my_organizations');const org=orgs?.[0];if(!user||!org){setError('Your Proper OS workspace is not active.');setSaving(false);return;}
    const jobTitle=String(fd.get('jobTitle'));const inviteOption=String(fd.get('inviteOption'));const access=fd.getAll('access').map(String);const selectedWorker=String(fd.get('workerType'));const workerType=jobTitle==='Sales Representative'?'1099_contractor':selectedWorker;const roleKey=roleMap[jobTitle]||'read_only';const accessLevel=['company_owner','company_manager','company_admin'].includes(roleKey)?'full_company':'branch_department';
    const {data:member,error:memberError}=await supabase.from('workforce_members').insert({organization_id:org.organization_id,branch_id:String(fd.get('branch'))||null,first_name:String(fd.get('firstName')).trim(),last_name:String(fd.get('lastName')).trim(),email:String(fd.get('email')).trim(),worker_type:workerType,department:String(fd.get('department')),job_title:jobTitle,status:String(fd.get('status')),access_level:accessLevel,access_notes:access.join(', '),account_status:'not_invited',invitation_role_key:roleKey,invitation_requested_at:null,welcome_letter_status:inviteOption==='welcome'?'queued':'not_requested',created_by:user.id}).select('id').single();
    if(memberError){setError(memberError.message);setSaving(false);return;}
    const docs=[['job_offer',fd.get('jobOffer')],['welcome_letter',fd.get('welcomeLetter')]] as const;
    for(const [type,value] of docs){if(value instanceof File&&value.size>0){const safe=value.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${org.organization_id}/${member.id}/${type}-${Date.now()}-${safe}`;const {error:uploadError}=await supabase.storage.from('hr-documents').upload(path,value,{contentType:value.type||undefined,upsert:false});if(uploadError){setError(`Profile saved, but ${type.replace('_',' ')} upload failed: ${uploadError.message}`);setSaving(false);return;}const {error:docError}=await supabase.from('workforce_onboarding_documents').insert({organization_id:org.organization_id,workforce_member_id:member.id,document_type:type,file_name:value.name,file_path:path,content_type:value.type||null,file_size_bytes:value.size,created_by:user.id});if(docError){setError(`File uploaded, but its HR record failed: ${docError.message}`);setSaving(false);return;}}}
    if(inviteOption!=='none'){const {error:inviteError}=await supabase.functions.invoke('invite-workforce',{body:{workforce_member_id:member.id,organization_id:org.organization_id,action:'invite'}});if(inviteError){setError(`Profile saved, but the Proper OS invitation email failed: ${inviteError.message}`);setSaving(false);return;}}
    setMessage(inviteOption==='none'?'Team member saved without an account invitation.':inviteOption==='welcome'?'Team member saved, the welcome letter was stored in HR, and the Proper OS account invitation email was sent.':'Team member saved and the Proper OS account invitation email was sent.');form.reset();setSaving(false);
  }
  return <><div className="top"><div><h1>Human Resources</h1><p>Add employees and contractors, assign branch/department/access, securely attach onboarding documents, and invite them to Proper OS.</p></div></div><form className="card" onSubmit={submit}><div className="form-section" style={{borderTop:0,marginTop:0,paddingTop:0}}><h3>Team member</h3><div className="form-grid"><label className="field">First name<input name="firstName" required/></label><label className="field">Last name<input name="lastName" required/></label><label className="field">Email<input name="email" type="email" required/></label><label className="field">Employee or Contractor<select name="workerType"><option value="w2_employee">Employee (W-2)</option><option value="1099_contractor">Contractor (1099)</option></select></label><label className="field">Job title<select name="jobTitle" defaultValue="Sales Representative">{jobTitles.map(x=><option key={x}>{x}</option>)}</select></label><label className="field">Branch<select name="branch" required>{branches.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label className="field">Department<select name="department">{departments.map(([label,value])=><option value={value} key={`${label}-${value}`}>{label}</option>)}</select></label><label className="field">Status<select name="status"><option value="onboarding">Onboarding</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div></div><div className="form-section"><h3>Assigned access</h3><p>The selected modules are saved with the workforce profile; the job title maps to the enforceable Proper OS role used when the account is invited.</p><div className="module-grid">{accessOptions.map(x=><label className="card" style={{padding:'14px',boxShadow:'none'}} key={x}><input type="checkbox" name="access" value={x}/> {x}</label>)}</div></div><div className="form-section"><h3>Onboarding</h3><div className="form-grid"><label className="field">Job offer<input name="jobOffer" type="file" accept=".pdf,.doc,.docx"/></label><label className="field">Welcome letter<input name="welcomeLetter" type="file" accept=".pdf,.doc,.docx"/></label><label className="field">Invite options<select name="inviteOption"><option value="invite">Send Proper OS invite</option><option value="welcome">Store welcome letter + send Proper OS invite</option><option value="none">Save without sending invite</option></select></label></div></div>{error&&<p className="error">{error}</p>}{message&&<p>{message}</p>}<div className="modal-actions"><button className="secondary" type="reset">Clear</button><button className="primary button-auto" disabled={saving}>{saving?'Saving…':'Add team member'}</button></div></form></>;
}
